In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('pokemon_alopez247.csv')

In [3]:
df.head()

Number        Name Type_1  Type_2  Total  HP  Attack  Defense  Sp_Atk  \
0       1   Bulbasaur  Grass  Poison    318  45      49       49      65   
1       2     Ivysaur  Grass  Poison    405  60      62       63      80   
2       3    Venusaur  Grass  Poison    525  80      82       83     100   
3       4  Charmander   Fire     NaN    309  39      52       43      60   
4       5  Charmeleon   Fire     NaN    405  58      64       58      80   

   Sp_Def  ...  Color  hasGender  Pr_Male Egg_Group_1  Egg_Group_2  \
0      65  ...  Green       True    0.875     Monster        Grass   
1      80  ...  Green       True    0.875     Monster        Grass   
2     100  ...  Green       True    0.875     Monster        Grass   
3      50  ...    Red       True    0.875     Monster       Dragon   
4      65  ...    Red       True    0.875     Monster       Dragon   

   hasMegaEvolution Height_m Weight_kg  Catch_Rate      Body_Style  
0             False     0.71       6.9          45       quadruped  
1             False     0.99      13.0          45       quadruped  
2              True     2.01     100.0          45       quadruped  
3             False     0.61       8.5          45  bipedal_tailed  
4             False     1.09      19.0          45  bipedal_tailed  

[5 rows x 23 columns]

In [4]:
df.columns

Index(['Number', 'Name', 'Type_1', 'Type_2', 'Total', 'HP', 'Attack',
       'Defense', 'Sp_Atk', 'Sp_Def', 'Speed', 'Generation', 'isLegendary',
       'Color', 'hasGender', 'Pr_Male', 'Egg_Group_1', 'Egg_Group_2',
       'hasMegaEvolution', 'Height_m', 'Weight_kg', 'Catch_Rate',
       'Body_Style'],
      dtype='object')

In [5]:
df=df.drop(columns=['Number', 'Name', 'Type_1', 'Type_2','Generation','Color', 'hasGender', 'Pr_Male', 'Egg_Group_1', 'Egg_Group_2',
       'hasMegaEvolution', 'Height_m', 'Weight_kg','Body_Style'])

In [6]:
df.head()

Total  HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  isLegendary  Catch_Rate
0    318  45      49       49      65      65     45        False          45
1    405  60      62       63      80      80     60        False          45
2    525  80      82       83     100     100     80        False          45
3    309  39      52       43      60      50     65        False          45
4    405  58      64       58      80      65     80        False          45

In [7]:
df.columns

Index(['Total', 'HP', 'Attack', 'Defense', 'Sp_Atk', 'Sp_Def', 'Speed',
       'isLegendary', 'Catch_Rate'],
      dtype='object')

In [8]:
df.isnull().sum()

Total          0
HP             0
Attack         0
Defense        0
Sp_Atk         0
Sp_Def         0
Speed          0
isLegendary    0
Catch_Rate     0
dtype: int64

In [9]:
df.duplicated().any()

True

In [10]:
df=df.drop_duplicates().reset_index(drop=True)

In [11]:
df.duplicated().any()

False

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 709 entries, 0 to 708
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Total        709 non-null    int64
 1   HP           709 non-null    int64
 2   Attack       709 non-null    int64
 3   Defense      709 non-null    int64
 4   Sp_Atk       709 non-null    int64
 5   Sp_Def       709 non-null    int64
 6   Speed        709 non-null    int64
 7   isLegendary  709 non-null    bool 
 8   Catch_Rate   709 non-null    int64
dtypes: bool(1), int64(8)
memory usage: 45.1 KB


In [13]:
df=df[['Total', 'HP', 'Attack', 'Defense', 'Sp_Atk', 'Sp_Def', 'Speed','Catch_Rate','isLegendary']]
       

In [14]:
df

Total   HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  Catch_Rate  \
0      318   45      49       49      65      65     45          45   
1      405   60      62       63      80      80     60          45   
2      525   80      82       83     100     100     80          45   
3      309   39      52       43      60      50     65          45   
4      405   58      64       58      80      65     80          45   
..     ...  ...     ...      ...     ...     ...    ...         ...   
704    680  126     131       95     131      98     99          45   
705    600  108     100      121      81      95     95           3   
706    600   50     100      150     100     150     50           3   
707    600   80     110       60     150     130     70           3   
708    600   80     110      120     130      90     70           3   

     isLegendary  
0          False  
1          False  
2          False  
3          False  
4          False  
..           ...  
704         True  
705         True  
706         True  
707         True  
708         True  

[709 rows x 9 columns]

In [15]:
df['isLegendary']=df['isLegendary'].map(lambda x: 1 if x else 0)

In [16]:
df

Total   HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  Catch_Rate  \
0      318   45      49       49      65      65     45          45   
1      405   60      62       63      80      80     60          45   
2      525   80      82       83     100     100     80          45   
3      309   39      52       43      60      50     65          45   
4      405   58      64       58      80      65     80          45   
..     ...  ...     ...      ...     ...     ...    ...         ...   
704    680  126     131       95     131      98     99          45   
705    600  108     100      121      81      95     95           3   
706    600   50     100      150     100     150     50           3   
707    600   80     110       60     150     130     70           3   
708    600   80     110      120     130      90     70           3   

     isLegendary  
0              0  
1              0  
2              0  
3              0  
4              0  
..           ...  
704            1  
705            1  
706            1  
707            1  
708            1  

[709 rows x 9 columns]

In [17]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [18]:
X

Total   HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  Catch_Rate
0      318   45      49       49      65      65     45          45
1      405   60      62       63      80      80     60          45
2      525   80      82       83     100     100     80          45
3      309   39      52       43      60      50     65          45
4      405   58      64       58      80      65     80          45
..     ...  ...     ...      ...     ...     ...    ...         ...
704    680  126     131       95     131      98     99          45
705    600  108     100      121      81      95     95           3
706    600   50     100      150     100     150     50           3
707    600   80     110       60     150     130     70           3
708    600   80     110      120     130      90     70           3

[709 rows x 8 columns]

In [19]:
y

0      0
1      0
2      0
3      0
4      0
      ..
704    1
705    1
706    1
707    1
708    1
Name: isLegendary, Length: 709, dtype: int64

In [20]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3 , random_state=12)

In [21]:
X_train.shape , X_test.shape , y_train.shape , y_test.shape

((496, 8), (213, 8), (496,), (213,))

In [22]:
y_test

462    0
161    0
11     0
556    0
275    0
      ..
449    0
510    0
310    0
398    0
164    0
Name: isLegendary, Length: 213, dtype: int64

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
scaler=StandardScaler()

In [25]:
y_train

649    0
6      0
476    1
210    0
228    0
      ..
642    0
241    1
253    0
390    0
667    0
Name: isLegendary, Length: 496, dtype: int64

In [26]:
X_train_scaled =scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [27]:
X_test_scaled

array([[ 1.12367841,  0.64122587, -0.86673673, ...,  1.70918223,
         0.46178849, -0.91515735],
       [-1.40588666, -1.11142676, -1.89635853, ...,  0.39988016,
        -0.43587216,  2.02726732],
       [-0.23144573, -0.33247004, -1.03834037, ...,  0.39988016,
         0.10272423, -0.71899571],
       ...,
       [-1.0716227 ,  0.05700832, -1.10698182, ..., -0.61015287,
        -0.97446855,  1.63494403],
       [-0.52053888, -0.33247004,  0.33448869, ..., -0.75978739,
        -0.25634003,  0.26181252],
       [-0.27661654,  0.05700832,  0.50609233, ..., -0.34829245,
        -0.97446855, -0.13051077]])

In [28]:
X_train_scaled

array([[-1.28844256, -0.91668758, -0.86673673, ..., -1.17128233,
        -0.18452718,  2.02726732],
       [-0.96321277, -0.95563541, -0.93537819, ..., -0.19865793,
        -0.86674927, -0.71899571],
       [ 1.43987404,  0.25174751,  1.70731775, ...,  0.02579385,
         1.71851341, -1.26824831],
       ...,
       [-0.99934941, -0.7219484 , -0.1803222 , ..., -0.72237876,
        -0.97446855, -0.71899571],
       [-1.58656988, -1.11142676, -0.6951331 , ..., -1.47055137,
        -0.25634003,  2.02726732],
       [-0.863837  , -0.91668758,  0.16288506, ..., -1.20869096,
        -1.40534567,  1.0464591 ]])

In [30]:
from sklearn.svm import SVC

In [31]:
svc=SVC()

In [32]:
svc.fit(X_train_scaled , y_train)

SVC()

In [35]:
from sklearn.model_selection import GridSearchCV

In [36]:
parameters={
         'C':[1,0.1,10,2,],
         'kernel':['linear','poly','rbf','sigmoid']
         
}

In [37]:
clf=GridSearchCV(svc,
                 param_grid=parameters,
                 
                 cv=10
                )

In [38]:
clf.fit(X_train_scaled,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid={'C': [1, 0.1, 10, 2],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [39]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [41]:
clf.best_score_

0.9798367346938773

In [42]:
y_pred=clf.predict(X_test_scaled)

In [44]:
from sklearn.metrics import confusion_matrix

In [45]:
conf_mat = confusion_matrix(y_test,y_pred)
conf_mat

array([[204,   0],
       [  0,   9]])

In [46]:
true_positive = conf_mat[0][0]
false_positive = conf_mat[0][1]
false_negative = conf_mat[1][0]
true_negative = conf_mat[1][1]

In [47]:
Accuracy = (true_positive + true_negative) / (true_positive +false_positive + false_negative + true_negative)
Accuracy

1.0

In [48]:
y_test[:20]

462    0
161    0
11     0
556    0
275    0
286    0
597    0
697    0
611    0
394    0
14     0
380    1
408    0
229    0
691    0
344    0
629    1
97     0
186    0
392    0
Name: isLegendary, dtype: int64

In [49]:
y_pred[:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0])

In [50]:
import pickle

In [51]:
pickle.dump(scaler,open('scaler.pkl','wb'))
pickle.dump(svc,open('svc.pkl','wb'))